from pathlib import Path
real_file = Path("day_01_basics.py")
print("Checking a real file:")
print(f"Does it exist:{real_file.exists()}")
print(f"Is it a file:{real_file.is_file()}")
print("_____________________")
fake_file = Path("Dragon_wing.png")
print("Checking a fake file:")
print(f"Does file exist:{fake_file.exists()}")
print(f"Is it a file:{fake_file.is_file()}")
print("--------------------")
folder = Path("new_folder")
print(folder)
print(folder.is_dir())
current_folder = Path("")
print(current_folder)
print(current_folder.is_dir())